Algoritmo "Aprovado_ou_Reprovado"
// Descrição   : Leia a média de um aluno. Se média = 7 ? Aprovado. Caso contrário ? Reprovado
// Autor(a)    : Juan Manuel
// Data atual  : 26/02/2026
Var
media: real
Inicio
 escreva("Digite a média do aluno: ")
   leia(media)

   se (media >= 7) entao
      escreval("Aluno APROVADO")
   senao
      escreval("Aluno REPROVADO")
   fimse
Fimalgoritmo