Algoritmo "Intervalo"
// Descrição   : Leia um número e informe se ele está entre 10 e 50.
// Autor(a)    : Juan Manuel
// Data atual  : 26/02/2026
Var
numero: real
Inicio
 escreva("Digite um número: ")
   leia(numero)

   se (numero >= 10) e (numero <= 50) entao
      escreval("O número está entre 10 e 50.")
   senao
      escreval("O número não está entre 10 e 50.")
   fimse

Fimalgoritmo