Algoritmo "SEU_NOME"
// Disciplina  : Lógica de Programação
// Professor   : André Olímpio 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
  NOME:CARACTER


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("digite seu nome: ")
   leia(nome)
   escreva("ola, " ,nome, " seja bem vindo")

Fimalgoritmo